using NUnit.Framework;

namespace Transpire.Analysis.Tests.Generators;

internal static class EqualityGeneratorTests
{
	[Test]
	public static async Task GenerateWithMissingEqualityMarkupAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			public partial record Customer(
				Guid Id, [property: Excluded] string Name, [property: Ordered(3)] uint Age);
			""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[],
			[]);
	}

	[Test]
	public static async Task GenerateWithExcludedPropertyAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, [property: Excluded] string Name, uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithExcludedDefinedPropertyAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, uint Age)
			{
				[Excluded] 
				public string? Name { get; }
			}
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithOrderedPropertyAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, [property: Ordered(3)] string Name, uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(this.Name, other.Name) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Name);
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithOrderedDefinedPropertyAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, uint Age)
			{
				[Ordered(3)] 
				public string? Name { get; }
			}
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<string?>.Default.Equals(this.Name, other.Name) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Name);
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithMultipleExcludedAndOrderedPropertiesAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				[property: Ordered(2)] Guid Id, [property: Excluded] string Name, [property: Ordered(1)] uint Age, [property: Excluded] string EmailAddress);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithGenericRecordAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer<T>(
				[property: Ordered(2)] Guid Id, [property: Excluded] string Name, [property: Ordered(1)] uint Age, T Address);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer<T>
				: global::System.IEquatable<Customer<T>>
			{
				public virtual bool Equals(Customer<T>? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(this.Address, other.Address));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					hash.Add(this.Address);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_T_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithConstraintsAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			internal partial record Customer<T>([property: Ordered(0)] string Name) where T : struct;
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			internal partial record class Customer<T>
				: global::System.IEquatable<Customer<T>>
			{
				public virtual bool Equals(Customer<T>? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(this.Name, other.Name));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Name);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_T_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateWithNamespaceAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable

			namespace Entities;
		
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, [property: Excluded] string Name, [property: Ordered(3)] uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			namespace Entities;
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Entities.Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateInternalRecordAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable

			namespace Entities;
		
			[EqualityMarkup]
			internal partial record Customer(
				Guid Id, [property: Excluded] string Name, [property: Ordered(3)] uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			namespace Entities;
			
			internal partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Entities.Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateSealedRecordAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable

			namespace Entities;
		
			[EqualityMarkup]
			internal sealed partial record Customer(
				Guid Id, [property: Excluded] string Name, [property: Ordered(3)] uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			namespace Entities;
			
			internal sealed partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Entities.Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateAbstractRecordAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable

			namespace Entities;
		
			[EqualityMarkup]
			internal abstract partial record Customer(
				Guid Id, [property: Excluded] string Name, [property: Ordered(3)] uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			namespace Entities;
			
			internal abstract partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Age);
					hash.Add(this.Id);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Entities.Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}

	[Test]
	public static async Task GenerateStructRecordAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record struct Customer(
				Guid Id, [property: Excluded] string Name, uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record struct Customer
				: global::System.IEquatable<Customer>
			{
				public bool Equals(Customer other) =>
					global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
					global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age);
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}
}