using NUnit.Framework;

namespace Transpire.Analysis.Tests.Generators;

internal static class EqualityGeneratorTests
{
	[Test]
	public static async Task GenerateAsync()
	{
		var code =
			"""
			using Transpire;
			using System;

			#nullable enable
			
			[EqualityMarkup]
			public partial record Customer(
				Guid Id, [property: Equality(3)] string Name, uint Age);
			""";

		var generatedCode =
			""""
			// <auto-generated/>
			
			#nullable enable
			
			public partial record class Customer
				: global::System.IEquatable<Customer>
			{
				public virtual bool Equals(Customer? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
						global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(this.Name, other.Name) &&
						global::System.Collections.Generic.EqualityComparer<global::System.Guid>.Default.Equals(this.Id, other.Id) &&
						global::System.Collections.Generic.EqualityComparer<uint>.Default.Equals(this.Age, other.Age));
				
				public override int GetHashCode()
				{
					var hash = new global::System.HashCode();			
					hash.Add(this.Name);
					hash.Add(this.Id);
					hash.Add(this.Age);
					return hash.ToHashCode();
				}
			}
			
			"""";

		await TestAssistants.RunGeneratorAsync<EqualityGenerator>(code,
			[("Customer_EqualityMarkup.g.cs", generatedCode)],
			[]);
	}
}