using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;
using Transpire.Analysis.Extensions;
using Transpire.Analysis.Generators.Models;

namespace Transpire.Analysis.Generators.Builders;

internal sealed class EqualityBuilder
{
	internal EqualityBuilder(RecordModel model)
	{
		this.Model = model;

		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		var recordNamespace = model.Namespace;

		indentWriter.WriteLines(
			$$"""
			// <auto-generated/>
			
			#nullable enable
			
			""");

		var @namespace = this.Model.Namespace;

		if (!string.IsNullOrWhiteSpace(@namespace))
		{
			indentWriter.WriteLines(
				$"""
				namespace {@namespace};
				
				""");
		}

		var accessibility = model.DeclaredAccessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.Private => "private",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => string.Empty
		};

		var derivation =
			model.IsSealed && model.TypeKind != TypeKind.Struct ?
				"sealed " :
				model.IsAbstract ?
					"abstract " :
					string.Empty;

		var typeKind =
			model.TypeKind == TypeKind.Class ?
				"class" :
				"struct";

		indentWriter.WriteLines(
			$$"""
			{{accessibility}} {{derivation}}partial record {{typeKind}} {{this.Model.ClassName}}
				: global::System.IEquatable<{{this.Model.ClassName}}>
			{
			""");

		indentWriter.Indent++;
		this.BuildEquals(indentWriter);
		indentWriter.WriteLine();
		this.BuildGetHashCode(indentWriter);
		indentWriter.Indent--;

		indentWriter.WriteLine("}");

		this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = $"{this.Model.FullyQualifiedName.GenerateFileName()}_EqualityMarkup.g.cs";
	}

	private void BuildEquals(IndentedTextWriter indentWriter)
	{
		var indentSize = 0;

		if (this.Model.TypeKind == TypeKind.Class)
		{
			var allowOverriding = this.Model.IsSealed ? string.Empty : "virtual ";
			indentWriter.WriteLines(
				$$"""
				public {{allowOverriding}}bool Equals({{this.Model.ClassName}}? other) =>
					(object)this == other ||
						(other is not null &&
						this.EqualityContract == other.EqualityContract &&	
				""");
			indentSize = 2;
		}
		else
		{
			indentWriter.WriteLines(
				$$"""
				public bool Equals({{this.Model.ClassName}} other) =>
				""");
			indentSize = 1;
		}

		indentWriter.Indent += indentSize;

		for (var i = 0; i < this.Model.Properties.Length; i++)
		{
			var property = this.Model.Properties[i];
			var trailingCode = 
				i == this.Model.Properties.Length - 1 ? 
					this.Model.TypeKind == TypeKind.Struct ?
						";" :
						");" : 
					" &&";
			indentWriter.WriteLine(
				$"global::System.Collections.Generic.EqualityComparer<{property.FullyQualifiedTypeName}>.Default.Equals(this.{property.Name}, other.{property.Name}){trailingCode}");
		}

		indentWriter.Indent -= indentSize;
	}

	private void BuildGetHashCode(IndentedTextWriter indentWriter)
	{
		indentWriter.WriteLines(
			"""
			public override int GetHashCode()
			{
				var hash = new global::System.HashCode();			
			""");
		indentWriter.Indent++;

		foreach (var property in this.Model.Properties)
		{
			indentWriter.WriteLine(
				$"hash.Add(this.{property.Name});");
		}

		indentWriter.Indent--;
		indentWriter.WriteLines(
			"""
				return hash.ToHashCode();
			}
			""");
	}

	internal string FileName { get; }
	internal RecordModel Model { get; }
	internal SourceText Text { get; private set; }
}