using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;
using Transpire.Analysis.Extensions;
using Transpire.Analysis.Models;

namespace Transpire.Analysis.Generators.Builders;

internal sealed class EqualityBuilder
{
	internal EqualityBuilder(RecordModel model)
	{
		this.Model = model;

		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		var recordNamespace = model.Namespace;

		indentWriter.WriteLines(
			$$"""
			// <auto-generated/>
			
			#nullable enable
			
			""");

		var @namespace = this.Model.Namespace;

		if (!string.IsNullOrWhiteSpace(@namespace))
		{
			indentWriter.WriteLines(
				$"""
				namespace {@namespace};
				
				""");
		}

		var accessibility = model.DeclaredAccessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.Private => "private",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => string.Empty
		};

		var derivation =
			model.IsSealed ?
				"sealed " :
				model.IsAbstract ?
					"abstract " :
					string.Empty;
		// TODO: I don't think we want to do this unless it was
		// explicitly declared before on the record.
		var typeKind =
			model.TypeKind == TypeKind.Class ?
				"class" :
				"struct";

		indentWriter.WriteLines(
			$$"""
			{{accessibility}} {{derivation}}partial {{typeKind}} record {{this.Model.ClassName}}
				: global::System.IEquatable<{{this.Model.ClassName}}>
			{
			""");

		// TODO: Equals() and GetHashCode() generation.
		indentWriter.Indent++;
		this.BuildEquals(indentWriter);
		indentWriter.WriteLine();
		this.BuildGetHashCode(indentWriter);
		indentWriter.Indent--;

		indentWriter.WriteLine("}");

		this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = $"{this.Model.FullyQualifiedName.GenerateFileName()}_EqualityMarkup.g.cs";
	}

	private void BuildEquals(IndentedTextWriter indentWriter)
	{
		indentWriter.WriteLines(
			$$"""
			public bool Equals({{this.Model.ClassName}} other) =>
				(object)this == other ||
					((object)other != null &&
					this.EqualityContract == other.EqualityContract &&	
			""");
		indentWriter.Indent += 2;

		for (var i = 0; i < this.Model.Properties.Length; i++)
		{
			var property = this.Model.Properties[i];
			var trailingAnd = i == this.Model.Properties.Length - 1 ? string.Empty : " &&";
			indentWriter.WriteLine(
				$"global::System.Collections.Generic.EqualityComparer<{property.FullyQualifiedTypeName}>.Default.Equals(this.{property.Name}, other.{property.Name}){trailingAnd}");
		}

		indentWriter.Indent -= 2;
	}

	private void BuildGetHashCode(IndentedTextWriter indentWriter)
	{
		indentWriter.WriteLines(
			"""
			public override int GetHashCode()
			{
			    var hash = new global::System.HashCode();			
			""");
		indentWriter.Indent++;

		foreach (var property in this.Model.Properties)
		{
			indentWriter.WriteLine(
				$"hash.Add(this.{property.Name});");
		}

		indentWriter.Indent--;
		indentWriter.WriteLines(
			"""
			    return hash.ToHashCode();
			}
			""");
	}

	internal string FileName { get; }
	internal RecordModel Model { get; }
	internal SourceText Text { get; private set; }
}