using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.CodeDom.Compiler;
using System.Text;
using Transpire.Analysis.Extensions;
using Transpire.Analysis.Models;

namespace Transpire.Analysis.Builders;

internal sealed class ExcludePropertiesBuilder
{
	internal ExcludePropertiesBuilder(RecordModel model)
	{
		this.Model = model;

		using var writer = new StringWriter();
		using var indentWriter = new IndentedTextWriter(writer, "\t");

		var recordNamespace = model.Namespace;

		indentWriter.WriteLines(
			$$"""
			// <auto-generated/>
			
			#nullable enable
			
			""");

		var @namespace = this.Model.Namespace;

		if (!string.IsNullOrWhiteSpace(@namespace))
		{
			indentWriter.WriteLines(
				$"""
				namespace {@namespace};
				
				""");
		}

		var accessibility = model.DeclaredAccessibility switch
		{
			Accessibility.Public => "public",
			Accessibility.Internal => "internal",
			Accessibility.Protected => "protected",
			Accessibility.ProtectedOrInternal => "protected internal",
			Accessibility.Private => "private",
			Accessibility.ProtectedAndInternal => "private protected",
			_ => string.Empty
		};

		var derivation = 
			model.IsSealed ? 
				"sealed " :
				model.IsAbstract ?
					"abstract " :
					string.Empty;
		var typeKind = 
			model.TypeKind == TypeKind.Class ?
				"class" : 
				"struct";

		indentWriter.WriteLines(
			$$"""
			{{accessibility}} {{derivation}}partial {{typeKind}} record {{this.Model.GetClassName()}}
			{
			""");

		// TODO: Equals() and GetHashCode() generation.

		indentWriter.WriteLine("}");

		this.Text = SourceText.From(writer.ToString(), Encoding.UTF8);
		this.FileName = $"{this.Model.BusinessObject.FullyQualifiedName.GenerateFileName()}_GeneratorSerialization.g.cs";
	}

	internal string FileName { get; }
	internal RecordModel Model { get; }
	internal SourceText Text { get; private set; }
}